language: python
env:
    - TOX_ENV=py27
    - TOX_ENV=py35
    - TOX_ENV=flake8
python: 2.7
install:
  - pip install tox
script: tox -e $TOX_ENV
after_success: 
  - pip install coveralls
  - coveralls