language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements-test.txt
  - pip install coveralls
script: nosetests -s servicebook/tests/ --with-coverage --cover-package=servicebook
after_success: coveralls