language: python
python:
  - "2.7"
  - "3.5"
  - "flake8"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install coveralls
script: nosetests -s servicebook/tests/ --with-coverage --cover-package=servicebook --cover-html
after_success: coveralls